<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rkk_hand_bringup</name>
  <version>0.0.1</version>
  <description>Launch files bringing up rkk-hand-solver and rkk_hand_bridge together.</description>
  <maintainer email="anastasia.panaretou@rokoko.com">Rokoko</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rkk_hand_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
