"""Default parameter values, in one place so they are easy to change."""

import math

SOLVER_HOST = "127.0.0.1"
SOLVER_PORT = 12277
RECONNECT_DELAY_S = 0.5
STAMP_SOURCE = "auto"

PARENT_FRAME_ID = ""
PUBLISH_TF = False

PUBLISH_MARKERS = False
MARKER_RATE_HZ = 40.0
MARKER_LIFETIME_S = 0.5
MARKER_JOINT_SCALE = 1.0
MARKER_MAX_JOINT_RADIUS_M = 0.010
MARKER_HAND_SPACING_M = 0.45

CALIBRATE_FACING_RAD = 0.0
CALIBRATE_MAX_DISAGREEMENT_RAD = math.radians(30.0)
CALIBRATE_DELAY_S = 5.0
